name: Build

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew clean check build --stacktrace

  gametest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        optional-dependencies: [minimal, full]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - uses: gradle/actions/setup-gradle@v4
      - if: matrix.optional-dependencies == 'minimal'
        run: ./gradlew runGameTestServer -Pruntime_jei=false -Pruntime_mekanism=false --stacktrace
      - if: matrix.optional-dependencies == 'full'
        run: ./gradlew runGameTestServer --stacktrace
